#!/bin/bash

if [ $1 ];then
    DEV_LIST=$(losetup -n -O NAME -j $1)
else
    DEV_LIST=$(losetup -n -O NAME)
fi

for dev in $DEV_LIST; do

    MOUNTED_PARTITIONS=`df |grep $dev | awk '{print $1}'`
    for part in $MOUNTED_PARTITIONS; do
	echo "Umount loop partition $part"
	basename=`basename $part`
	sudo umount -f -q $part "$PWD/$basename"
	if [ -d $PWD/$basename ];then
	    sudo rmdir "$PWD/$basename"
	fi
    done
    
    echo "Detach loop device $dev with image $(losetup -n -O BACK-FILE $dev)"
    sudo losetup --detach $dev
    
done

