#!/bin/bash

if [ $1 ];then
    DEV_LIST=$(losetup -n -O NAME -j $1)
else
    DEV_LIST=$(losetup -n -O NAME)
fi

for dev in $DEV_LIST; do
    echo "Detach loop device $dev with image $(losetup -n -O BACK-FILE $dev)"
    sudo losetup --detach $dev

    for part in $dev""*; do
	echo "Umount loop partition $part"
	basename=`basename $part`
	sudo umount -f -q $part "$PWD/$basename"
	if [ -d $PWD/$basename ];then
	    sudo rmdir "$PWD/$basename"
	fi
    done
done


#A GPT partition stores a backup header at the end of the disk. 
#If you have resized the underlying device, the backup header will be somewhere in the middle. 
#The first step is to move the partition header to the end of the disk.
#sgdisk -e /dev/sda
#-e, --move-second-header: Move backup GPT data structures to the end of the disk. 
#Use this option if you've added disks to a RAID array, thus creating a virtual disk with space that follows the backup GPT data structures. 
#This command moves the backup GPT data structures to the end of the disk, where they belong.

